version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discord-reaction-bot
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - bot-network

  mongodb:
    image: mongo:5
    container_name: discord-bot-mongodb
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-password}
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - bot-network

volumes:
  mongodb-data:
    name: discord-bot-mongodb-data

networks:
  bot-network:
    name: discord-bot-network
    driver: bridge